display:
  width: 800
  height: 600
  update_frequency: 60

target:
  x: 0
  y: 0
  distance: 0.3

drone:
  mass_max: 1
  mass_min: 0.2             # Kilograms
  inertia: 1            # Kilogram meters squared
  gravity: 1
  motors:
    - [-0.5, 0, 0, 50]
    - [0, 0, 0, 50]
    - [0.5, 0, 0, 50]    # X offset from drone center, Y offset from drone center, rotation relative to drone center, thrust
    